### ISSUE TITLE
Use initContainers instead of containers

### ISSUE THREAD

**Issue by codejamninja** [GluuFederation/gluu-docker#72]
Is there a reason `containers` is being used instead of `initContainers` for the init config?

https://github.com/GluuFederation/gluu-docker/blob/3.1.5/examples/kubernetes/minikube/config/load-config.yaml#L16

```yaml
            claimName: config-volume-claim
      containers:
        - name: config-init-load
```

https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
